import { Flex, VStack } from '@chakra-ui/react';
import Head from 'next/head';
import SignUp from '../components/login/SignUp';
import styles from '../styles/Home.module.css';
import Header from '../components/resources/header';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Poli - Collaboration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <Flex height="100vh" background="gray.100" >
          <SignUp />
        </Flex>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
